# Site
name: "Patrick Lamber"
title: "Random thoughts about productivity software."
description: "IT Geek focusing on Microsoft 365 productivity solutions."
logo: 'assets/images/logo.svg'
baseurl: 
google_analytics: 'UA-85617783-1'
disqus: 'nubo'
follow-twitter: 'http://www.twitter.com/patricklamber'
follow-instagram: 'http://www.instagram.com/lambersports'
follow-facebook: 'https://www.facebook.com/patrick.lamber'
follow-linkedin: 'https://www.linkedin.com/in/plamber/'
follow-github: 'https://github.com/plamber'
mailchimp-list: 
#'https://nubo.us3.list-manage.com/subscribe?u=6c85dfdd00be275ce46cdfa5c&id=b2f4f20705'
include: ["_pages"]
permalink: /:title/
show_drafts: false

# Authors
authors:
  plamber:
    name: Patrick Lamber
    display_name: Patrick Lamber
    gravatar: a2c337b39c3335cb89037db1e61ab262
    email: patrick@nubo.eu
    web: http://www.nubo.eu
    twitter: https://twitter.com/patricklamber
    description: "IT Geek focusing on Microsoft collaboration software."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-target-blank
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
