# Site
name: "Malter Analytics"
title: "Analytics and Data Science Blog"
description: ""
logo: 'assets/images/Malter-Analytics-Logo.png'
baseurl: 
google_analytics: 'UA-137918066-1'
disqus: 'danmalter'
follow-twitter: 'http://www.twitter.com/danmalter'
follow-instagram: 'http://www.instagram.com/malteranalytics'
follow-facebook: 'https://www.facebook.com/malteranalytics'
#follow-linkedin: 'https://www.linkedin.com/in/malteranalytics/'
follow-github: 'https://github.com/malteranalytics'
mailchimp-list: 
#
include: ["_pages"]
permalink: /:title/
show_drafts: false

# Authors
authors:
  danny:
    name: Danny Malter
    display_name: Danny
    gravatar: d8f2524cf47fb8fa03ba52ad8579238f
    #email: email@malteranalytics.com
    web: 
    twitter: https://twitter.com/danmalter
    description: "Data Scientist"
  drew:
    name: Andrew Malter
    display_name: Drew
    gravatar: 22bbf73d98a84d2a896c474e26a1a8fe
    web: 
    twitter: https://www.instagram.com/malteranalytics/?hl=en
    description: "Data Scientist"
  danny_drew:
    name: Danny Malter & Drew Malter
    display_name: Danny & Drew
    gravatar: d8f2524cf47fb8fa03ba52ad8579238f
    #email: email@malteranalytics.com
    web: 
    #twitter: https://twitter.com/danmalter
    description: "Data Scientist"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-target-blank
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
